# Generated by Django 5.1.7 on 2025-03-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('attack_type', models.CharField(max_length=100)),
                ('target_industry', models.CharField(max_length=100)),
                ('financial_loss_million', models.FloatField()),
                ('affected_users', models.BigIntegerField()),
                ('attack_source', models.CharField(max_length=100)),
                ('vulnerability_type', models.CharField(max_length=100)),
                ('defense_mechanism', models.CharField(max_length=100)),
                ('resolution_time_hours', models.IntegerField()),
            ],
        ),
    ]
